<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_UspsEndiciaShipping
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<div style='background: #FFF; border: 1px solid #0091DB;'>
    <div style='padding:10px;float: left;text-align: left; vertical-align:bottom;'>
        <a href='https://www.endicia.com/resellers/multi-rate-service-signup?id=ITVZ7OCP6RC8EB1W' target='_blank'>
        <img src='https://www.endicia.com/Content/images/endicia-logo.png' style='float: left;' />
        </a>
        <b>
            <?= /* @noEscape */ __('The Endicia Professional plan enables you to seamlessly integrate USPS® fulfillment into your shipping operations and create shipping labels using an advanced, feature-rich shipping solution. Obtain a Account Number and Passphrase') ?> 
            <a href='https://www.endicia.com/resellers/multi-rate-service-signup?id=ITVZ7OCP6RC8EB1W' target='_blank'><?= ('Sign Up Now') ?></a>
        </b>
    </div>
</div>